/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package istiq0mah;

import javax.swing.JOptionPane;

/**
 *
 * @author Ammar Dzakwan
 */
public class Frame2Home extends javax.swing.JFrame {

    /**
     * Creates new form Frame2Home
     */
    public Frame2Home() {
        initComponents();
    }
    
    public Frame2Home(String nama) {
        initComponents();
        SelamatDatang.setText("Selamat Datang Wahai " + nama + "...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tilawah = new javax.swing.JLabel();
        Sholawat = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        SelamatDatang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tilawah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TilawahMouseClicked(evt);
            }
        });
        getContentPane().add(Tilawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 250, 240));

        Sholawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SholawatMouseClicked(evt);
            }
        });
        getContentPane().add(Sholawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 290, 240));

        LogOutBtn.setText("Keluar");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        SelamatDatang.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        SelamatDatang.setText("Selamat Datang Wahai Hamba Allah....");
        getContentPane().add(SelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 550, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Assalamu’alaikum.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin pergi?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        //0=yes, 1=no, 2=cancel

        if (input == 0) {

            Frame1Salam f1 = new Frame1Salam();
            f1.setLocationRelativeTo(null);
            f1.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void TilawahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TilawahMouseClicked
        // TODO add your handling code here:
        Frame3Tilawah f3 = new Frame3Tilawah();
        f3.setLocationRelativeTo(null);
        f3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TilawahMouseClicked

    private void SholawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SholawatMouseClicked
        // TODO add your handling code here:
        Frame4Sholawat f4 = new Frame4Sholawat();
        f4.setLocationRelativeTo(null);
        f4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SholawatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JLabel Sholawat;
    private javax.swing.JLabel Tilawah;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
